/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _INTSTORE_H_RPCGEN
#define _INTSTORE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct arr {
	int Arr[8];
};
typedef struct arr arr;

#define INTSTORE_PROG 0x31415926
#define INTSTORE_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define APPEND_INTSTORE 1
extern  char ** append_intstore_1(arr *, CLIENT *);
extern  char ** append_intstore_1_svc(arr *, struct svc_req *);
#define QUERY_INTSTORE 2
extern  char ** query_intstore_1(int *, CLIENT *);
extern  char ** query_intstore_1_svc(int *, struct svc_req *);
#define REMOVE_INTSTORE 3
extern  char ** remove_intstore_1(int *, CLIENT *);
extern  char ** remove_intstore_1_svc(int *, struct svc_req *);
extern int intstore_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define APPEND_INTSTORE 1
extern  char ** append_intstore_1();
extern  char ** append_intstore_1_svc();
#define QUERY_INTSTORE 2
extern  char ** query_intstore_1();
extern  char ** query_intstore_1_svc();
#define REMOVE_INTSTORE 3
extern  char ** remove_intstore_1();
extern  char ** remove_intstore_1_svc();
extern int intstore_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_arr (XDR *, arr*);

#else /* K&R C */
extern bool_t xdr_arr ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_INTSTORE_H_RPCGEN */
