/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "IntStore.h"


void
intstore_prog_1(char *host)
{
	CLIENT *clnt;
	char * *result_1;
	arr  append_intstore_1_arg;
	char * *result_2;
	int  query_intstore_1_arg;
	char * *result_3;
	int  remove_intstore_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, INTSTORE_PROG, INTSTORE_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = append_intstore_1(&append_intstore_1_arg, clnt);
	if (result_1 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = query_intstore_1(&query_intstore_1_arg, clnt);
	if (result_2 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = remove_intstore_1(&remove_intstore_1_arg, clnt);
	if (result_3 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	intstore_prog_1 (host);
exit (0);
}
