/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _INTSTORE_H_RPCGEN
#define _INTSTORE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

struct arr {
	int Arr[8];
};
typedef struct arr arr;

//most node bas structure from https://www.geeksforgeeks.org/how-to-create-a-linked-list-in-c/
// Define the structure of Node
typedef struct Node {
  
    // Data field. Can add more data according to our need
    int data;

    // Pointer to the next node
    struct Node *next;
	struct Node *prev;
} Node;

int printAllNodes(void);

int sortAllNodes(void);

int swapNodes(Node *first, Node *second);

int itterateThroughList(int pos, Node* cur);

#define INTSTORE_PROG 0x31415926
#define INTSTORE_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define APPEND_INTSTORE 1
extern  char ** append_intstore_1(arr *, CLIENT *);
extern  char ** append_intstore_1_svc(arr *, struct svc_req *);
#define QUERY_INTSTORE 2
extern  char ** query_intstore_1(int *, CLIENT *);
extern  char ** query_intstore_1_svc(int *, struct svc_req *);
#define REMOVE_INTSTORE 3
extern  char ** remove_intstore_1(int *, CLIENT *);
extern  char ** remove_intstore_1_svc(int *, struct svc_req *);
#define checkIn_INTSTORE 4
extern  char ** checkin_intstore_1(void *, CLIENT *);
extern  char ** checkin_intstore_1_svc(void *, struct svc_req *);
extern int intstore_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);


#else /* K&R C */
#define APPEND_INTSTORE 1
extern  char ** append_intstore_1();
extern  char ** append_intstore_1_svc();
#define QUERY_INTSTORE 2
extern  char ** query_intstore_1();
extern  char ** query_intstore_1_svc();
#define REMOVE_INTSTORE 3
extern  char ** remove_intstore_1();
extern  char ** remove_intstore_1_svc();
#define checkIn_INTSTORE 4
extern  char ** checkin_intstore_1();
extern  char ** checkin_intstore_1_svc();
extern int intstore_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_arr (XDR *, arr*);

#else /* K&R C */
extern bool_t xdr_arr ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_INTSTORE_H_RPCGEN */
