/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "IntStore.h"

char **
append_intstore_1_svc(arr *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return &result;
}

char **
query_intstore_1_svc(int *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return &result;
}

char **
remove_intstore_1_svc(int *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return &result;
}

char **
checkin_intstore_1_svc(void *argp, struct svc_req *rqstp)
{
	static char * result;
	printf("Test5\n");
	result = "succesful connection";

	printf("Test6\n%s\nTest7\n",result);
	return &result;
}
