/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "date.h"
//add
#include <time.h>

long *
bin_date_1_svc(void *argp, struct svc_req *rqstp)
{
	static long result;

	/*
	 * insert server code here
	 */
	//add
	result = time((long *)0);

	return &result;
}

char **
str_date_1_svc(long *argp, struct svc_req *rqstp)
{
	static char *result;

	/*
	 * insert server code here
	 */
	//add
	printf("str_date_1_svc: start!\n");
	result = ctime( argp);
	
	return &result;
}
